-- Run this entire file ONCE in Supabase: Project → SQL Editor → New query →
-- paste this whole file → Run. This is the only "migration" step this
-- project needs — there's no ORM/migration tool involved.

-- ─── Tables ──────────────────────────────────────────────────────────

create table if not exists tracked_flights (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users(id) on delete cascade,
  origin         text not null,
  destination    text not null,
  departure_date date not null,
  return_date    date,
  target_price   integer not null,
  current_price  integer not null,
  lowest_price   integer not null,
  created_at     timestamptz not null default now()
);

create index if not exists tracked_flights_user_id_idx on tracked_flights(user_id);

create table if not exists price_history (
  id                bigint generated by default as identity primary key,
  tracked_flight_id bigint not null references tracked_flights(id) on delete cascade,
  price             integer not null,
  checked_at        timestamptz not null default now()
);

create index if not exists price_history_tracked_flight_id_idx on price_history(tracked_flight_id);

-- ─── Row Level Security ─────────────────────────────────────────────
--
-- This is REQUIRED, not optional. Without Prisma's direct/superuser
-- connection, the app talks to Postgres through Supabase's PostgREST layer
-- using the signed-in user's session JWT. RLS is what actually stops user A
-- from reading/editing user B's rows — the API route code checks ownership
-- too, but RLS is the real enforcement boundary at the database level.

alter table tracked_flights enable row level security;
alter table price_history enable row level security;

create policy "select own tracked flights"
  on tracked_flights for select
  using (auth.uid() = user_id);

create policy "insert own tracked flights"
  on tracked_flights for insert
  with check (auth.uid() = user_id);

create policy "update own tracked flights"
  on tracked_flights for update
  using (auth.uid() = user_id);

create policy "delete own tracked flights"
  on tracked_flights for delete
  using (auth.uid() = user_id);

-- price_history rows are only ever accessed through their parent
-- tracked_flight, so gate access via a subquery on ownership.

create policy "select price history of own flights"
  on price_history for select
  using (
    exists (
      select 1 from tracked_flights
      where tracked_flights.id = price_history.tracked_flight_id
      and tracked_flights.user_id = auth.uid()
    )
  );

create policy "insert price history for own flights"
  on price_history for insert
  with check (
    exists (
      select 1 from tracked_flights
      where tracked_flights.id = price_history.tracked_flight_id
      and tracked_flights.user_id = auth.uid()
    )
  );

-- ─── Note on the scheduled job ──────────────────────────────────────
--
-- scripts/checkPrices.js runs outside any single user's session, so it
-- authenticates with SUPABASE_SERVICE_ROLE_KEY, which deliberately bypasses
-- RLS (that's what "service role" means — trusted server-side code only,
-- never shipped to the browser). That's by design: the job needs to read
-- and update every user's tracked flights to check prices for everyone.
